# frozen_string_literal: true

require 'fileutils'

vagrant_host_dir = 'vagrant_host_dir'
vagrant_guest_dir = '/mnt/vagrant'
script = <<-SCRIPT
  set -x
  curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable=traefik --disable=servicelb --disable=local-storage" sh -
  echo "source <(kubectl completion bash)" >> ~/.bashrc
  echo "alias k=kubectl" >> ~/.bashrc
  echo "complete -F __start_kubectl k" >> ~/.bashrc
  echo "export KUBECONFIG=/etc/rancher/k3s/k3s.yaml" >> ~/.bashrc
  curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
SCRIPT

FileUtils.mkdir_p(vagrant_host_dir)

Vagrant.configure(2) do |config|
  config.vm.box = 'bento/ubuntu-20.04'
  config.vm.hostname = 'k3s'
  config.vm.provider :virtualbox do |vb|
    vb.name = 'k3s'
    vb.gui = false
    vb.memory = 4096
    vb.cpus = 4
  end
  config.vm.synced_folder vagrant_host_dir, vagrant_guest_dir
  config.vm.provision :shell, inline: script
end
